name: C Program CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile
        run: gcc -Wall -Werror -o dbSQL dbSQLcmpl.c

      - name: Run program
        run: ./dbSQL
